### ISSUE TITLE
/wp-admin/plugin-install.php throws Fatal error

### ISSUE THREAD

**Issue by uwew** [bonny/Developer-Loggers-for-Simple-History#1]
Hello there,

I really like the idea of the developer add-on for Simple History, but turns out I can't use it: it throws a fatal error when trying to access /wp-admin/plugin-install.php i.e. add plugins (returning a blank page):

`PHP Fatal error:  Cannot redeclare plugins_api() (previously declared in /home/user/public_html/site/wp-admin/includes/plugin-install.php:101) in /home/user/public_html/site/wp-admin/includes/plugin-install.php on line 183`

I turned some all options off and then back on -  turns out it only throws the error when enabling the "AvailableUpdatesLogger".

- Uwe Willenbacher

**Comment by bonny** [comment]
I can reproduce this myself, but I made a change now that perhaps fixes it anyway (I think I included a file that was not really needed to be included..). Can you check if the master version here on GitHub works for you?

**Comment by bonny** [comment]
(🎉 because this is the very first issue for this plugin!)

**Comment by uwew** [comment]
Yup, indeed, that fixed it - Thank you very much,

- Uwe Willenbacher
