### ISSUE TITLE
nonce in javascript, image in context

### ISSUE THREAD

**Issue by 1ucay** [bonny/Developer-Loggers-for-Simple-History#3]
It is possible to extended secure solution for javascript loggers? I think some nonce field. If I send to url 1000x request per second, it can shutdown websites, because of logger. I know, that these logges are only for developing, but catch javascript error so it nice on production websites :)
So best it would be, if there was some secure option to log entry only 1x per second. 

Also I have idea..I have bug report on website, which can handle printscreen of webpage.. so it is possible to add to the context array POST file (in this example image, but custom file it would be nice), disable resize in native WP function and only handle upload.  Thx

**Comment by bonny** [comment]
Thanks for the issue. However I'm closing this because it's very old. Also this plugin will probably not receive any updates.
