### ISSUE TITLE
Wordpress Hook

### ISSUE THREAD

**Issue by Santana1053** [bonny/Developer-Loggers-for-Simple-History#4]
I would like to be able to install this plugin on over 80 websites to use with the Slack integration. Obviously this would be very tedious to do on each site individually. Are there any actions, filters or constants that would let me set the settings of this plugin with code?

**Comment by bonny** [comment]
Maybe! Just updated the plugin and added the filters that whould make this possible. Download the latest version (0.5) and check out the examples file:

https://github.com/bonny/Developer-Loggers-for-Simple-History/blob/master/examples.php

**Comment by Santana1053** [comment]
`simple_history/developer_loggers/slackit/settings` only runs on Developer Logger settings save.

**Comment by bonny** [comment]
Hm.. No it is called from within function get_settings(), so it's also called for example after something has been logged to the database. Or am I missing something?

**Comment by Santana1053** [comment]
After adding both of these filters to my plugin on my local testing website, I triggered an event that logged to Simple History, but it did not output anything to slack. After I went into the Developer Settings and just clicked the save button, and then repeated the trigger, then it logged to Slack

**Comment by Santana1053** [comment]
I did some debugging for this. I added the filter to enable the slackit logger. While looking at the Developer logger settings, it is shown as checked, but after checking the database, the value is not set until after the settings are saved. Just adding the filters is not causing the settings to be saved. Same thing is happening for the filter to add the webhook.
